application/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', "FeedController@index")
    ->name('home');
{//Auth
    Route::post('/register', "Authenticate@create");
    Route::get('/register', "Authenticate@register")
        ->name("register");
    Route::get('/login', "Authenticate@login")
        ->name("login");

    Route::post('/login', "Authenticate@authenticate");

    Route::get('/logout', "Authenticate@logout")
        ->middleware('auth')
        ->name("logout");
}
Route::resource('/feed', "FeedController");

application/app/Feed.php
<?php

namespace App;

use App\Services\Feed\TypeInterface;
use App\Services\Feed\Type\Rss;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Ramsey\Uuid\Uuid;

class Feed extends Model
{
    public    $incrementing = false;
    protected $table        = 'feed';
    protected $fillable     = [
        'url',
    ];

    /**
     * The "booted" method of the model.
     *
     * @return void
     */
    protected static function booted()
    {
        static::creating(function (self $feed) {
            if (!$feed->id) {
                $feed->id = Uuid::uuid4()->toString();
            }
        });
        static::saving(function (self $feed) {
            if (!$feed->user_id) {
                $feed->user_id = Auth::id();
            }
        });
    }

    /**
     * @param TypeInterface $feed
     * @return bool
     */
    public function hydrateFromReader(TypeInterface $feed): bool
    {
        $this->title = $feed->getTitle();
        $this->link  = $feed->getLink();
        if ($feed instanceof Rss) {
            $this->description = $feed->getDescription();
            $this->image       = $feed->getImage();
        }

        return true;
    }
}

application/app/Http/Controllers/FeedController.php
<?php

namespace App\Http\Controllers;

use App\Feed;
use App\Services\Feed\Reader;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class FeedController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data =
            Feed::query()
                ->where('user_id', Auth::id())
                ->paginate(10);

        return
            view('feed.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return
            $this->edit(new Feed());
    }

    /**
     * @param \App\Http\Requests\Feed $request
     * @return \Illuminate\Http\Response
     */
    public function store(\App\Http\Requests\Feed $request)
    {
        $message = 'Error occurred when adding a new feed';
        $feed    = new Feed($request->validated());

        if ($reader = Reader\Wrapper\Xml\Url::fromUrl($feed->url)) {
            if (
                $feed->hydrateFromReader($reader)
                && $feed->save()
            ) {
                return
                    redirect()
                        ->route(
                            'feed.show',
                            $feed,
                            302,
                            [
                                'X-Created' => 1,
                            ]
                        )
                        ->with('success', 'Feed added.');
            }
        } else {
            $message = 'Provided URL failed to produce a valid feed';
        }

        $request->flash();

        return
            redirect()
                ->route('feed.create')
                ->with('error', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Feed $feed
     * @return \Illuminate\Http\Response
     */
    public function show(Feed $feed)
    {
        $this->authorizeFeed($feed);
        $entries =
            Reader\Wrapper\Xml\Url::fromUrl($feed->url)->getEntries();

        return
            view(
                'feed.show',
                compact('feed', 'entries')
            );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Feed $feed
     * @return \Illuminate\Http\Response
     */
    public function edit(Feed $feed)
    {
        $this->authorizeFeed($feed);

        return
            view(
                'feed.edit',
                compact('feed')
            );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Feed $request
     * @param  \App\Feed $feed
     * @return \Illuminate\Http\Response
     */
    public function update(\App\Http\Requests\Feed $request, Feed $feed)
    {
        $this->authorizeFeed($feed);
        $message = 'Feed not updated';
        $feed->fill($request->validated());

        if ($reader = Reader\Wrapper\Xml\Url::fromUrl($feed->url)) {
            if (
                $feed->hydrateFromReader($reader)
                && $feed->save()
            ) {

                return
                    redirect()
                        ->route(
                            'feed.show',
                            $feed,
                            302,
                            [
                                'X-Updated' => 1,
                            ]
                        )
                        ->with('success', 'Feed updated');
            }
        } else {
            $message = 'Provided URL failed to produce a valid feed';
        }

        return
            redirect()
                ->route('feed.edit', $feed)
                ->with('error', $message);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Feed $feed
     * @return \Illuminate\Http\Response
     */
    public function destroy(Feed $feed)
    {
        $this->authorizeFeed($feed);

        if ($feed->delete()) {
            return
                redirect()
                    ->route(
                        'feed.index',
                        [],
                        302,
                        [
                            'X-Deleted' => 1,
                        ]
                    )
                    ->with('success', 'Feed deleted');
        }

        return
            redirect()
                ->route('feed.show', $feed)
                ->with('error', 'Feed not deleted');
    }

    /**
     * @param Feed $feed
     */
    protected function authorizeFeed(Feed $feed)
    {
        if (Gate::denies(Feed::class, $feed)) {
            abort(404);
        }
    }
}

application/resources/views/feed/autocomplete.blade.php
<script>
    $("{{$source}}").autocomplete({
        source   : function (request, response) {
            $.ajax({
                url    : "{{route('company.autocomplete')}}",
                type   : "POST",
                data   : {
                    name: request.term
                },
                success: function (data) {
                    if (data.length > 0) {
                        response(data);
                    }
                }
            });
        },
        minLength: 1,
        autoFocus: true,
        select   : function (event, ui) {
            $("{{$destination}}").each(function (index, value) {
                $(value).val(ui.item.id);
            });

            return true;
        }
    });
</script>

application/resources/views/feed/edit.blade.php
@extends('layouts.master')

@section('title', $feed->exists ? 'Edit feed':'Create a new feed')
@section('content')
    <div class="container-fluid pt-3">
        <div class="card">
            <form method="POST"
                  action="{{ $feed->exists ? route('feed.update',$feed):route('feed.store') }}"
                  enctype="multipart/form-data">
                @if($feed->exists)
                    @method('PUT')
                @endif
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="url">URL</label>
                        <input class="form-control" id="url" placeholder="Enter feed URL" name="url"
                               value="{{old('url',$feed->url)}}">
                        @error('url')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
@stop

application/resources/views/feed/index.blade.php
@extends('layouts.master')

@section('title', 'Feeds list')
@section('content')
    @include('feed.list',['paginate'=>true])
@stop

application/resources/views/feed/list.blade.php
<div class="container-fluid pt-3">
    <div class="card">
        <div class="card-header border-0">
            <h3 class="card-title">Feeds</h3>
            <div class="card-tools">
                <a href="{{route('feed.create')}}" class="btn btn-tool btn-sm">
                    <i class="fa fa-plus"></i>
                </a>
            </div>
        </div>
        <div class="card-body table-responsive p-0">
            <table class="table table-striped table-valign-middle">
                <thead>
                <tr>
                    <th>Logo</th>
                    <th>Title</th>
                    <th>Related link</th>
                    <th>Date added</th>
                </tr>
                </thead>
                <tbody>
                @foreach($data as $feed)
                    <tr>
                        <td>
                            <img src="{{$feed->image ?? asset('dist/img/boxed-bg.jpg')}}"
                                 alt="Feed image"
                                 class="img-size-32 mr-2">
                        </td>
                        <td>
                            <a href="{{route('feed.show',$feed->id)}}">
                                {{$feed->title}}
                            </a>
                        </td>
                        <td>
                            <a href="{{$feed->link}}">
                                {{$feed->link}}
                            </a>
                        </td>
                        <td>
                            {{$feed->created_at}}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            @if($paginate)
                <div class="card-header border-0">
                    <div class="card-tools">
                        {{$data->links()}}
                    </div>
                </div>
            @endif
        </div>
    </div>
</div>

application/resources/views/feed/show.blade.php
@extends('layouts.master')

@section('title', 'Feed details')
@section('content')
    <div class="container-fluid pt-3">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary card-outline">
                    <h3 class="text-center">Feed details</h3>
                    <div class="card-body box-profile">
                        <div class="text-center">
                            <img class="feed-img img-fluid"
                                 src="{{$feed->image ?? asset('dist/img/boxed-bg.jpg')}}"
                                 alt="Feed image">
                        </div>

                        <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                                <b>Url</b> <a class="float-right">{{$feed->url}}</a>
                            </li>
                            <li class="list-group-item">
                                <b>Title</b> <a class="float-right">{{$feed->title}}</a>
                            </li>
                            <li class="list-group-item">
                                <b>Link</b> <a class="float-right">{{$feed->link}}</a>
                            </li>
                        </ul>

                        <form action="{{route('feed.destroy',$feed->id)}}" method="POST" class="text-center">
                            @csrf
                            @method('DELETE')
                            <a href="{{route('feed.edit',$feed->id)}}" class="btn btn-primary">
                                Edit
                            </a>
                            <button type="submit" class="btn btn-danger">
                                Delete
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card card-success card-outline">
                    <h3 class="text-center">Entries</h3>
                    <div class="card-body table-responsive p-0">
                        <table class="table table-striped table-valign-middle">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Related link</th>
                                <th>Content</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($entries as $entry)
                                <tr>
                                    <td>
                                        {{$entry->getTitle()}}
                                    </td>
                                    <td>
                                        <a href="{{$entry->getLink()}}">
                                            {{$entry->getLink()}}
                                        </a>
                                    </td>
                                    <td>
                                        {!!$entry->getContent()!!}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop